packages:
  - playground/*
  - packages/*

autoInstallPeers: true

ignoreWorkspaceRootCheck: true

catalogs:
  build:
    tsdown: ^0.15.1
    tsx: ^4.20.5
    typescript: ^5.9.2
    unplugin: ^2.3.10
    unplugin-utils: ^0.3.0

    vite: ^7.1.5
    vite-plugin-dts: ^4.4.0
  icons:
    '@iconify-json/catppuccin': ^1.2.16
    '@iconify-json/hugeicons': ^1.2.14
    '@iconify/utils': ^3.0.1

  lint:
    '@antfu/eslint-config': ^5.2.2

    eslint: ^9.35.0
  plugins:
    vite-dev-rpc: ^1.1.0
  test:
    vitest: ^3.2.4

  unocss:
    '@unocss/core': ^66.5.1
    '@unocss/preset-web-fonts': ^66.5.1
    '@unocss/preset-wind4': ^66.5.1

    unocss: ^66.5.1
  utils:
    '@types/node': ^24.4.0
    debug: ^4.4.3

    esno: ^4.8.0
    tinyglobby: ^0.2.14
  vue:
    '@vitejs/plugin-vue': ^6.0.1
    '@vueuse/core': ^13.9.0
    vue: ^3.5.21
    vue-tsc: ^3.0.6

onlyBuiltDependencies:
  - core-js
  - esbuild

shamefullyHoist: true

strictPeerDependencies: false
